version: '3.8'

services:
  #database section
  sqlserverdb:
    container_name: sqlserverdb
    environment:
      SA_PASSWORD: "Passw0rd!"
      ACCEPT_EULA: "Y"
    restart: always
    volumes: 
      - sqlserver_data:/var/lib/sqlserver/data
    ports:
      - "1435:1433"

  mysqldb:
    container_name: mysqldb
    environment:
      SA_PASSWORD: "Passw0rd!"
    restart: always
    volumes: 
      - mysql_data:/var/lib/sqlserver/data
    ports:
      - "3307:3306"