version: '3.8'

services:
  #database section
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  
  productdb:
    image: mysql:8.0.29

  customerdb:
    image: postgres:alpine3.16

  basketdb:
    image: redis:alpine

  inventorydb:
    image: mongo

  #infrastructure section
  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image:


  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  
  mysqldb:
    image: mysql:8.0.29

#network section
networks:
  default:
    name: cassie_microservices
    driver: bridge

#volumns section
volumes:
  sqlserver_data:
    name: sqlserver_data
  mysql_data:
    name: mysql_data
